version: "3.9"
services:
  qcadoo:
    image: qcadoo:local
    build:
      context: .
      dockerfile: ./qcadoo.Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./logs:/opt/qcadoo/mes-application/logs
    user: "${UID:-0}"

  db:
    image: postgres_qcadoo
    build:
      context: .
      dockerfile: ./postgres.Dockerfile
    restart: always
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-passwd
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: mes
    volumes:
      - ./database:/var/lib/postgresql/data
      - ./secrets:/run/secrets:ro

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080
    depends_on:
      - db